# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
