# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='functions',
            field=models.CharField(default='hello_world', max_length=1000),
            preserve_default=False,
        ),
    ]
