# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='submission_key',
            field=models.CharField(max_length=255),
        ),
    ]
