# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_auto_20170115_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='submission_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
